title: Doug's Website
email: doug@dsknr.com
description: >- # this means to ignore newlines until "baseurl:"
  A place for me to develop my ideas and serve as my home base on the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: _doug_skinner
github_username: doug-skinner

show_excerpts: true # set to false to remove excerpts on the homepage

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  recipes:
    output: true
    permalink: /:collection/:name
